# # Tetrodotoxin
# Copyright (c) 2023-present Matt Kaes and contributors

module(name = "godot")

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "ttx_cuda", version = "0.0.1")
local_path_override(
    module_name = "ttx_cuda",
    path = "../cuda",
)

godot_cpp_repository = use_repo_rule("//extension/build:sdk.bzl", "godot_cpp_repository")

godot_cpp_repository(
    name = "godot_cpp",
    build_file = "//extension/build:godot_cpp.BUILD.bazel",
    generator = "//extension/build:generate.py",
    profile = "//extension/build:profile.json",
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "pocketfft",
    build_file = "//demo/imaging/cpu:pocketfft.BUILD.bazel",
    sha256 = "2d90016da31a8cc1dd0ac0c89c1f2fb55df8f4ccc3f0386dcfbad09ac6d1c3ba",
    strip_prefix = "pocketfft-c90e55b3d529f8efa40ed01a20de22405f45fc65",
    type = "tar.gz",
    urls = ["https://codeload.github.com/mreineck/pocketfft/tar.gz/c90e55b3d529f8efa40ed01a20de22405f45fc65"],
)

godot_cpp_repository(
    name = "godot_cpp_web",
    bits = "32",
    build_file = "//extension/build:godot_cpp.BUILD.bazel",
    generator = "//extension/build:generate.py",
    profile = "//extension/build:profile.json",
)

bazel_dep(name = "tetro_toolchain", version = "0.1.0")
archive_override(
    module_name = "tetro_toolchain",
    sha256 = "c34c2230660426abefb7344305969b72ebb7cfe119e9adeaaa81d5533c7cd1f5",
    urls = ["https://github.com/tetrodotoxin-dev/Toolchain/releases/download/v0.1.0/tetro_toolchain-0.1.0-source.tar.gz"],
)

register_toolchains("@tetro_toolchain//:cc_toolchain_for_linux_x86_64", "@tetro_toolchain//:cc_toolchain_for_wasm32", "@tetro_toolchain//:cc_toolchain_for_windows_x64")

sdks = use_extension("@tetro_toolchain//:sdk.bzl", "dependencies")
sdks.release(
    name = "perimortem",
    archives = {
        "linux-x86_64-v3": "6c64132eebb13ef8db2458f77c3885c9cf1e0a6ff4ef72826397de53277510b3",
        "wasm32-emscripten": "0f04ee2af8c803e96b893430ea5215e448d79c41ef28d7c286086c9536330878",
    },
    project = "Perimortem",
    version = "0.1.0",
    deps = [],
)
sdks.release(
    name = "ttx",
    archives = {
        "linux-x86_64-v3": "930c5a1c770a841f9a04bc41264942373c70076805634e0cba8a5021d010e2a8",
        "wasm32-emscripten": "d5daa90ee9bddbb2b89a39ccd27bd6593eee667a3fae17ec45928694577cffcc",
    },
    project = "TTX",
    version = "0.1.0",
    deps = ["@perimortem"],
)
use_repo(sdks, "perimortem", "ttx")
