# # Tetrodotoxin
# Copyright (c) 2023-present Matt Kaes and contributors

load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "standard",
    srcs = ["standard.cpp"],
    hdrs = ["standard.hpp"],
    deps = ["//images", "//contracts"],
    visibility = ["//visibility:public"],
)
